version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers

    steps:
      - checkout
      - restore_cache:
          key: v1-commitlinter-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn clean verify
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - save_cache:
          key: v1-commitlinter-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

